import { useState, useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home = () => {
  const [transcription, setTranscription] = useState('')
  const [lines, setLines] = useState([]);
  
 useEffect(() => {
    setLines(transcription.split("."));
  }, [transcription]);
  
  const transcribe = async () => {
    console.log("starting")
    try {
      const response = await fetch('/api/transcribe', {
        method: 'POST',
      });
      const received = await response.json();
            const data= JSON.parse(received)
      const transcription = data.results.channels[0].alternatives[0].transcript;
      setTranscription(transcription)
    } catch (error) {
      console.error(error);
    }
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App + Deepgram Transcription</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Transcribe Me!
        </h1>
        <form >
          <button type='button' onClick={transcribe} className={styles.button}>Transcribe</button>
        </form>
        {transcription &&  <div className={styles.transcript} id="new-transcription">
      {lines.map((line, index) => {
        if (line.startsWith("Speaker 0:")) {
          return <p key={index}>{line}</p>
        } else {
          return <p key={index}>{line}</p>
        }
      })}
    </div>}
      </main>
    </div>
  )
}

export default Home
